"""Add identifier column

Revision ID: 378df1efc981
Revises: 
Create Date: 2023-10-28 23:57:51.430545

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '378df1efc981'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('age',
    sa.Column('AgeID', sa.Integer(), nullable=False),
    sa.Column('AgeGroup', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('AgeID')
    )
    op.create_table('day',
    sa.Column('DayID', sa.Integer(), nullable=False),
    sa.Column('DayName', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('DayID')
    )
    op.create_table('user',
    sa.Column('UserID', sa.Integer(), nullable=False),
    sa.Column('UserRole', sa.String(length=50), nullable=False),
    sa.Column('Email', sa.String(length=255), nullable=False),
    sa.Column('Password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('UserID'),
    sa.UniqueConstraint('Email')
    )
    op.create_table('daycare_owner',
    sa.Column('OwnerID', sa.Integer(), nullable=False),
    sa.Column('OwnerName', sa.String(length=255), nullable=False),
    sa.Column('Capacity', sa.Integer(), nullable=True),
    sa.Column('LicenseNumber', sa.String(length=100), nullable=True),
    sa.Column('FromTime', sa.Time(), nullable=True),
    sa.Column('ToTime', sa.Time(), nullable=True),
    sa.Column('Phone', sa.String(length=50), nullable=True),
    sa.Column('Street', sa.String(length=255), nullable=True),
    sa.Column('City', sa.String(length=100), nullable=True),
    sa.Column('State', sa.String(length=50), nullable=True),
    sa.Column('Zip', sa.String(length=10), nullable=True),
    sa.Column('SpecialNeeds', sa.String(length=10), nullable=True),
    sa.Column('Website', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['OwnerID'], ['user.UserID'], ),
    sa.PrimaryKeyConstraint('OwnerID')
    )
    op.create_table('parent',
    sa.Column('ParentID', sa.Integer(), nullable=False),
    sa.Column('ParentName', sa.String(length=255), nullable=False),
    sa.Column('NumberOfChildren', sa.Integer(), nullable=True),
    sa.Column('ChildrenAges', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['ParentID'], ['user.UserID'], ),
    sa.PrimaryKeyConstraint('ParentID')
    )
    op.create_table('volunteer',
    sa.Column('VolunteerID', sa.Integer(), nullable=False),
    sa.Column('FullName', sa.String(length=255), nullable=False),
    sa.Column('SSN', sa.String(length=50), nullable=True),
    sa.Column('Age', sa.Integer(), nullable=True),
    sa.Column('HoursAvailable', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['VolunteerID'], ['user.UserID'], ),
    sa.PrimaryKeyConstraint('VolunteerID')
    )
    op.create_table('daycare__ages_served',
    sa.Column('OwnerID', sa.Integer(), nullable=False),
    sa.Column('AgeID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['AgeID'], ['age.AgeID'], ),
    sa.ForeignKeyConstraint(['OwnerID'], ['daycare_owner.OwnerID'], ),
    sa.PrimaryKeyConstraint('OwnerID', 'AgeID')
    )
    op.create_table('daycare__days_of_operation',
    sa.Column('OwnerID', sa.Integer(), nullable=False),
    sa.Column('DayID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['DayID'], ['day.DayID'], ),
    sa.ForeignKeyConstraint(['OwnerID'], ['daycare_owner.OwnerID'], ),
    sa.PrimaryKeyConstraint('OwnerID', 'DayID')
    )
    op.create_table('volunteer__days_available',
    sa.Column('VolunteerID', sa.Integer(), nullable=False),
    sa.Column('DayID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['DayID'], ['day.DayID'], ),
    sa.ForeignKeyConstraint(['VolunteerID'], ['volunteer.VolunteerID'], ),
    sa.PrimaryKeyConstraint('VolunteerID', 'DayID')
    )
    op.drop_table('users')
    with op.batch_alter_table('daycares', schema=None) as batch_op:
        batch_op.add_column(sa.Column('identifier', sa.String(length=10), nullable=False))
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=200),
               nullable=False)
        batch_op.alter_column('rating',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.String(length=5),
               existing_nullable=False)
        batch_op.create_unique_constraint(None, ['identifier'])
        batch_op.drop_column('website')
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daycares', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('website', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('rating',
               existing_type=sa.String(length=5),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.String(length=200),
               type_=mysql.TEXT(),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.drop_column('identifier')

    op.create_table('users',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('volunteer__days_available')
    op.drop_table('daycare__days_of_operation')
    op.drop_table('daycare__ages_served')
    op.drop_table('volunteer')
    op.drop_table('parent')
    op.drop_table('daycare_owner')
    op.drop_table('user')
    op.drop_table('day')
    op.drop_table('age')
    # ### end Alembic commands ###
